# NumPy 01 - Arrays

In [1]:
import numpy as np

Die grundlegende Struktur in NumPy ist das mehrdimensionale __Array__, das Werte desselben numerischen Datentyps zusammenfasst. Die Dimensionen des Arrays werden __Axes__ (Achsen) genannt. Durch diese Form der Speicherung sind extrem schnelle mathematische Operationen auf allen Elementen des Arrays möglich (durch entsprechende unterliegende in C implementierte Funktionen), im Gegensatz zu den Listen von Python, deren Elemente alle von einem unterschiedlichen Typ sein können.

Die zugehörige Klasse heißt __np.ndarray__ (n-dimensional array). Sie kann einfach aus einem normalen Python-Array erzeugt werden.

### Grundlegende Funktionen

In [2]:
ex1 = np.array([[11,12],[21,22],[31,33]])
print('ndarray:')
print(ex1)
print(f'ndarray.dim: \t{ex1.ndim} \t(Anzahl der Achsen/Dimensionen)')
print(f'ndarray.size: \t{ex1.size} \t(Anzahl der Elemente)')
print(f'ndarray.shape: \t{ex1.shape} \t(Form des Arrays)')
print(f'ndarray.dtype: \t{ex1.dtype} \t(Datentyp)')


ndarray:
[[11 12]
 [21 22]
 [31 33]]
ndarray.dim: 	2 	(Anzahl der Achsen/Dimensionen)
ndarray.size: 	6 	(Anzahl der Elemente)
ndarray.shape: 	(3, 2) 	(Form des Arrays)
ndarray.dtype: 	int32 	(Datentyp)


### Arrays erzeugen

#### Aus Python-Arrays

In [3]:
ex2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype= float)
print(ex2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [4]:
print("ndarray.reshape")
print(ex2.reshape(3,4))

ndarray.reshape
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


#### Vordefinierte Arrays

In [5]:
print("(np.zeros((2,3),dtype=int)")
print(np.zeros((2,3),dtype=int))
print("np.ones((2,3),dtype=int)")
print(np.ones((2,3),dtype=int))
print("np.empty((2,3),dtype=int)")
print(np.empty((2,3),dtype=int))

(np.zeros((2,3),dtype=int)
[[0 0 0]
 [0 0 0]]
np.ones((2,3),dtype=int)
[[1 1 1]
 [1 1 1]]
np.empty((2,3),dtype=int)
[[1 1 1]
 [1 1 1]]


#### Arrays aus Wertbereichen

Mit __np.arange(start,stop,step)__ wird ein eindimensionales Array mit gegebenen Grenzen und gegebener Schrittweite erzeugt.

In [6]:

print(f'np.arange(3) -> {np.arange(3)}')
print(f'np.arange(1,3) -> {np.arange(1,3)}')
print(f'np.arange(1,10,2) -> {np.arange(1,10,2)}')
print(f'np.arange(10,1,-2) -> {np.arange(10,1,-2)}')
print(f'np.arange(1,2,0.1) -> {np.arange(1,2,.1)}')

np.arange(3) -> [0 1 2]
np.arange(1,3) -> [1 2]
np.arange(1,10,2) -> [1 3 5 7 9]
np.arange(10,1,-2) -> [10  8  6  4  2]
np.arange(1,2,0.1) -> [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


Mit __np.linspace(start,stop,samples)__ wird ein eindimensionales Array mit gegebenen Grenzen und gegebener Anzahl von Elementen erzeugt.

In [7]:
print(f'np.linspace(1,10,3) -> {np.linspace(1,10,3)}')
print(f'np.linspace(1,2,6) -> {np.linspace(1,2,6)}')

np.linspace(1,10,3) -> [ 1.   5.5 10. ]
np.linspace(1,2,6) -> [1.  1.2 1.4 1.6 1.8 2. ]


Mit __np.random.random((_shape_))__ kann ein Array aus Zufallszahlen erzeugt werden.

In [8]:
print('np.random.random((2,3)) ->') 
print(np.random.random((2,3)))
print(np.floor(10*np.random.random(3)))

np.random.random((2,3)) ->
[[0.52189798 0.03333745 0.49519502]
 [0.32288181 0.82684547 0.36944895]]
[8. 4. 2.]


In [9]:
def f(x,y):
    return 10*x+y

print(np.fromfunction(f,(5,4),dtype=int))

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


#### Funktionen auf Arrays

Eingebaute Funktionen wie __sum__ und __max__ lassen sich auf Arrays anwenden, als würde über eine Liste iteriert. Es kann auch über einzelne Achsen gearbeitet werden.

In [10]:
a = np.arange(1,13)
a = a.reshape(3,4)
print('Array a')
print(a)

print(f'a.sum() -> {a.sum()}')
print(f'a.prod() -> {a.prod()}')
print(f'a.min() -> {a.min()}')
print(f'a.max() -> {a.max()}')
print(f'a.sum(axis=0) -> {a.sum(axis=0)}')

Array a
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a.sum() -> 78
a.prod() -> 479001600
a.min() -> 1
a.max() -> 12
a.sum(axis=0) -> [15 18 21 24]


#### Universelle Funktionen
Viele Funktioen in Numpy sind __ufunc__, d.h. _universal functions_, die sowohl auf einzelne Werte als auch auf Arrays angewandt werden können. Auf Arrays wirken sie elementweise und ergeben wieder ein Array.

In [11]:
b = np.arange(1,5)
print('Array b: {b}')

print(f'b * 2 -> {b * 2}')
print(f'b - 1 -> {b - 1}')
print(f'b * b -> {b * b}')
print(f'b ** 2 -> {b ** 2}')
print(f'np.exp(b) -> {np.exp(b)}')
print(f'np.cos(b) -> {np.cos(b)}')


Array b: {b}
b * 2 -> [2 4 6 8]
b - 1 -> [0 1 2 3]
b * b -> [ 1  4  9 16]
b ** 2 -> [ 1  4  9 16]
np.exp(b) -> [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.cos(b) -> [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
