# NumPy

In [1]:
import numpy as np
a = np.linspace(0,9,10,dtype=int)

In [2]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a.shape

(10,)

In [4]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Slicing

In [5]:
a = [n for n in range(20)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [6]:
a[1:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [7]:
a[::-1]

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

## Broadcasting

In [8]:
matrix = np.array([[1,3,0],[-2,6,10]])
vector = ([3,1,9])

In [9]:
matrix * vector

array([[ 3,  3,  0],
       [-6,  6, 90]])

In [10]:
matrix @ vector

array([ 6, 90])

In [11]:
3 * matrix

array([[ 3,  9,  0],
       [-6, 18, 30]])