# Einführung NumPy II

In [1]:
import numpy as np
np.set_printoptions(precision=1,suppress=True)

## Rechnen mit NumPy-Arrays

### Arrays als Vektoren

NumPy ermöglicht Rechenoperationen auf Zahlen und Arrays. Tatsächlich lassen sich die Grundrechenarten auch auf Arrays anwenden, wenn sie verschiedene Dimension haben (wobei wir einfache Zahlen als Arrays der Dimension 0 betrachten), wenn es nur irgendwie "passt". Dies wird __Broadcasting__ genannt. Dabei wird der jeweilige Operand (+, -, *, /) komponentenweise angewandt:

In [22]:
x = 1
a = np.array([1,2,3])
m = np.array([[1,2,3],[4,5,6]])

print(f'{x} + {a} = {x + a}')
print(f'{x} + {m} = {x + m}')
print(f'{a} + {a} = {a + a}')
print(f'{a} + {m} = {a + m}')
print(f'{m} + {m} = {m + m}')

1 + [1 2 3] = [2 3 4]
1 + [[1 2 3]
 [4 5 6]] = [[2 3 4]
 [5 6 7]]
[1 2 3] + [1 2 3] = [2 4 6]
[1 2 3] + [[1 2 3]
 [4 5 6]] = [[2 4 6]
 [5 7 9]]
[[1 2 3]
 [4 5 6]] + [[1 2 3]
 [4 5 6]] = [[ 2  4  6]
 [ 8 10 12]]


## Rechnen mit Vektoren und Matrizen

Dadurch sind alle Rechenoperationen möglich, die für mathematische __Skalare__, __Vektoren__, __Matrizen__ oder allgemein __Tensoren__ definiert sind. Dies sind die Objekte, mit denen sich in der Mathematik die __Lineare Algebra__ beschäftigt.

#### Summen von Vektoren

Vektoren werden komponentenweise addiert:

In [2]:
v1 = np.array([3,0,-1])
v2 = np.array([1,0,4])
print(f'{v1} + {v2} = {v1+v2}')
print(f'{v1} - {v2} = {v1-v2}')

[ 3  0 -1] + [1 0 4] = [4 0 3]
[ 3  0 -1] - [1 0 4] = [ 2  0 -5]


Stimmt die Anzahl der Komponenten nicht überein, gibt es einen Fehler beim _Broadcasting_:

In [10]:
v3 = np.arange(4)
print(v1 + v3)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

Mathematisch unsinnig, aber möglich ist folgende Addition:

In [23]:
m = np.arange(12).reshape(4,3)
print(v1+m)

[[ 3  1  1]
 [ 6  4  4]
 [ 9  7  7]
 [12 10 10]]


#### Produkte mit Zahlen (_Skalaren_)

Arrays beliebiger Dimension können komponentenweise mit Zahlen multipliziert werden:

In [24]:
v = np.arange(6)
m = v.reshape(2,3)
print (5 * v)
print(0 * v)
print(-v)
print(5*m)

[ 0  5 10 15 20 25]
[0 0 0 0 0 0]
[ 0 -1 -2 -3 -4 -5]
[[ 0  5 10]
 [15 20 25]]


### Multiplikation von Matrizen mit Vektoren und Matrizen

Bei den mathematisch interessanten Multiplikationen zwischen Vektoren und Matrizen ist die komponentenweise Operation unsinnig. 

In [25]:
v1 = np.array([3,0,-1])
v2 = np.array([1,0,4])
m1 = np.array([[1,2,3],[1,2,3]])
m2 = np.array([[1,2],[3,4],[5,6]])

In [26]:
print(f'Mathematisch unsinnig: {v1} * {v2} =  {v1 * v2}')
print(f'Mathematisch unsinnig: {m1} * {v2} =  {m1 * v2}')

Mathematisch unsinnig: [ 3  0 -1] * [1 0 4] =  [ 3  0 -4]
Mathematisch unsinnig: [[1 2 3]
 [1 2 3]] * [1 0 4] =  [[ 1  0 12]
 [ 1  0 12]]


In der Mathematik macht zwischen Vektoren nur das __Skalarprodukt__ einen Sinn, bei dem zuerst komponentenweise multipliziert wird und dann alle Komponenten addiert werden. Daraus ensteht eine einfache Zahl, eben ein Skalar. Die Schreibweise ist dabei $v_1 \cdot v_2$ mit einem Punkt zwischen den Variablen, weswegen das Skalarprodukt auch __Punkt-Produkt__ (_dot product_) genannt wird:

In [30]:
print(f'Skalarprodukt: {v1} . {v2} = {np.dot(v1,v2)}')

Skalarprodukt: [ 3  0 -1] . [1 0 4] = -1


Auf ähnliche Weise werden auch Matrizen und Vektoren sowie Matrizen untereinander multipliziert:


In [31]:
print(f'{m1} {v1} = {np.dot(m1,v2)}')

[[1 2 3]
 [1 2 3]] [ 3  0 -1] = [13 13]


In [9]:
print(f'{m1} {m2} = {np.dot(m1,m2)}')

[[1 2 3]
 [1 2 3]] [[1 2]
 [3 4]
 [5 6]] = [[22 28]
 [22 28]]


Mit diesen Operationen lassen sich alle mathematischen Operationen der __Linearen Algebra__ durchfühen.