# Einführung NumPy I

In [1]:
import numpy as np

## Erzeugung von NumPy-Arrays

### Konvertierung aus Python-Strukturen

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
arr2 = np.array(range(1,10,2), dtype = float)
print(arr2)

[1. 3. 5. 7. 9.]


### Erzeugung mit Funktionen aus NumPy

### Low-Level-Funktion zur Erzeugung von NumPy-Arrays

In [4]:
arr = np.ndarray(shape=(3,2), dtype=float, order='F')
print(arr)

[[9.34577196e-307 1.69119873e-306]
 [9.34598246e-307 1.24611673e-306]
 [1.60218491e-306 1.11262266e-307]]


### Bessere Komfort-Funktionen

In [5]:
zeros = np.zeros(10,dtype = int)
ones = np.ones(10)

print(zeros, ones)

[0 0 0 0 0 0 0 0 0 0] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
arr4 = np.linspace(1,10,6)
print(arr4)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [6]:
twos = 2 * np.ones(10)
print(twos)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [7]:
empty = np.empty(5)
print(empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306
 1.10033512e+200]


#### Mehrdimensionale Arrays (z.B. Matrizen)

In [29]:
mat1 = np.arange(1,11).reshape(2,5)
print(mat1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
mat1  = np.random.rand(3,4)
print(mat1)

[[0.19373059 0.10452415 0.41993446 0.6514726 ]
 [0.24862336 0.09821639 0.66149572 0.51281828]
 [0.20181163 0.12880779 0.76390987 0.61057195]]


In [ ]:
mat2  = np.random.rand(3,4)
print(mat2)

In [37]:
mat3  = np.random.randint(1,10,(3,4))
print(mat3)

[[6 1 7 7]
 [1 5 1 6]
 [4 9 2 7]]


In [30]:
id = np.eye(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
diag = np.diag([5,2,-1])
print(diag)

[[ 5  0  0]
 [ 0  2  0]
 [ 0  0 -1]]
